# Generated by Django 5.1.15 on 2026-09-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, help_text='Tenant association. Nullable for cross-tenant Principal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('MANAGEMENT', 'Management'), ('HOD', 'Head of Department'), ('MENTOR', 'Mentor'), ('FACULTY', 'Faculty'), ('ACCOUNTANT', 'Accountant'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian'), ('PRINT_STAFF', 'Print Shop Staff'), ('LIBRARY_STAFF', 'Library Staff')], db_index=True, default='STUDENT', max_length=30),
        ),
    ]
