# Generated by Django 5.1.15 on 2026-09-06 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_number', models.CharField(db_index=True, help_text='Unique institutional employee code', max_length=50)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('LAB_INSTRUCTOR', 'Lab Instructor')], default='ASSISTANT_PROFESSOR', max_length=50)),
                ('qualification', models.CharField(help_text='e.g. Ph.D. in Computer Science, M.Tech', max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('VISITING', 'Visiting')], default='FULL_TIME', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_members', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['faculty_number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('college', 'faculty_number'), name='unique_faculty_number_per_college')],
            },
        ),
    ]
