# Generated by Django 5.1.15 on 2026-09-06 07:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('print_color', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Full Color')], default='BW', max_length=10)),
                ('print_side', models.CharField(choices=[('SINGLE', 'Single Sided'), ('DUPLEX', 'Double Sided (Duplex)')], default='SINGLE', max_length=10)),
                ('paper_size', models.CharField(choices=[('A4', 'Standard A4'), ('A3', 'Large A3')], default='A4', max_length=10)),
                ('binding_type', models.CharField(choices=[('NONE', 'No Binding'), ('STAPLE', 'Corner Staple (Free)'), ('SPIRAL', 'Spiral Coil Binding'), ('HARD_BINDING', 'Hardcover Book Binding')], default='NONE', max_length=20)),
                ('lamination', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Paid Online / Wallet'), ('ON_PICKUP', 'Pay Cash on Pickup')], default='ON_PICKUP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Order Received'), ('QUEUED', 'In Print Queue'), ('PRINTING', 'Printing in Progress'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed & Collected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bw_per_page', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6)),
                ('color_per_page', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('duplex_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('spiral_binding_cost', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6)),
                ('hard_binding_cost', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=6)),
                ('lamination_per_page', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=6)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
            ],
            options={
                'verbose_name_plural': 'Print Pricing',
            },
        ),
    ]
