# Generated by Django 5.1.15 on 2026-09-06 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. Main Gate 1, CSE Lab 2', max_length=150)),
                ('code', models.CharField(db_index=True, help_text='e.g. ZONE-GATE-1', max_length=50)),
                ('building', models.CharField(help_text='e.g. Academic Block A, Gatehouse', max_length=150)),
                ('floor', models.IntegerField(default=0, help_text='0 for Ground floor, 1 for 1st floor, etc.')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
            ],
            options={
                'ordering': ['building', 'floor', 'name'],
                'unique_together': {('college', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. Gate 1 North Walkway', max_length=150)),
                ('code', models.CharField(db_index=True, help_text='e.g. CAM-GATE-01', max_length=50)),
                ('camera_type', models.CharField(choices=[('DOME', 'Dome Camera'), ('BULLET', 'Bullet Camera'), ('PTZ', 'Pan-Tilt-Zoom (PTZ)'), ('FISHEYE', '360° Fisheye')], default='DOME', max_length=30)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('rtsp_url', models.CharField(blank=True, max_length=500)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='ONLINE', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(default='1080p', max_length=20)),
                ('fps', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.camerazone')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('college', 'code')},
            },
        ),
    ]
