# Generated by Django 5.1.15 on 2026-09-06 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('colleges', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ACTIVE', 'Active & Verified'), ('REVOKED', 'Revoked'), ('DISABLED', 'Disabled / Inactive')], db_index=True, default='ENROLLED', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('representation_hash', models.CharField(help_text='Secure irreversible one-way feature representation hash', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometrics_enrolled', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to='students.student')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLatestLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField()),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_location', to='students.student')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camerazone')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(default='SEARCH_LAST_SEEN', max_length=50)),
                ('reason', models.CharField(help_text='Mandatory institutional reason for tracking inquiry', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_queries', to='students.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.95, help_text='Inference confidence score between 0.0000 and 1.0000', max_digits=5)),
                ('event_type', models.CharField(choices=[('FACE_RECOGNITION', 'Automated Face Recognition'), ('BADGE_SCAN_CORROBORATION', 'Badge Corroboration'), ('PASSING_DETECTION', 'Zone Transit Detection')], default='FACE_RECOGNITION', max_length=30)),
                ('processing_status', models.CharField(choices=[('PROCESSED', 'Processed'), ('FLAGGED', 'Flagged for Review'), ('ARCHIVED', 'Archived')], db_index=True, default='PROCESSED', max_length=20)),
                ('snapshot_url', models.CharField(blank=True, help_text='Temporary signed edge snapshot path', max_length=500)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='students.student')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camerazone')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['college', 'student', '-detected_at'], name='tracking_de_college_5dae95_idx'), models.Index(fields=['college', 'camera', '-detected_at'], name='tracking_de_college_ccb25f_idx')],
            },
        ),
    ]
