# Generated by Django 5.1.15 on 2026-09-06 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('colleges', '0001_initial'),
        ('departments', '0002_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, help_text='e.g. CS301, PY102', max_length=50)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Laboratory / Practical'), ('HYBRID', 'Hybrid (Theory + Lab)')], default='THEORY', max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=4)),
                ('semester_number', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('syllabus', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='departments.department')),
            ],
            options={
                'ordering': ['course', 'semester_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.CharField(help_text='e.g. 2026-2027', max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subjects', to='academics.batch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='faculty.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='academics.subject')),
            ],
            options={
                'ordering': ['subject', 'faculty'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(help_text='e.g. Hall 304, Computer Lab 2', max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.batch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course', 'code'), name='unique_subject_code_per_course'),
        ),
        migrations.AddConstraint(
            model_name='facultysubject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subject', 'faculty', 'batch', 'academic_year'), name='unique_faculty_subject_batch_year'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['batch', 'day_of_week'], name='academics_t_batch_i_65888f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['faculty', 'day_of_week'], name='academics_t_faculty_a4b429_idx'),
        ),
    ]
