# Generated by Django 5.1.15 on 2026-09-06 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (0 - 39)'), ('MEDIUM', 'Medium Risk (40 - 69)'), ('HIGH', 'High Risk (70 - 89)'), ('CRITICAL', 'Critical Risk (90 - 100)')], db_index=True, default='LOW', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Composite risk index between 0.00 (Minimal Risk) and 100.00 (Critical Risk)', max_digits=5)),
                ('analysis_type', models.CharField(choices=[('ACADEMIC_EARLY_WARNING', 'Academic Early Warning'), ('ATTENDANCE_RISK', 'Attendance Defaulter Risk'), ('COMPREHENSIVE', 'Comprehensive Risk Evaluation')], default='ACADEMIC_EARLY_WARNING', max_length=40)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('missing_assignments_count', models.IntegerField(default=0)),
                ('average_marks_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('leave_days_count', models.IntegerField(default=0)),
                ('key_risk_drivers', models.JSONField(default=list, help_text='Natural-language explainable risk factors identified by the model')),
                ('suggested_interventions', models.JSONField(default=list, help_text='Targeted actionable advisory recommendations for mentors')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of academic metrics at evaluation time')),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('review_action_taken', models.CharField(blank=True, choices=[('COUNSELING_SCHEDULED', '1-on-1 Mentorship Counseling Scheduled'), ('REMEDIAL_ASSIGNED', 'Remedial Coursework & Tutoring Assigned'), ('PARENT_ADVISED', 'Parent / Guardian Contacted'), ('MONITORING', 'Continued Observation & Attendance Tracking'), ('NO_ACTION', 'No Immediate Action Required')], default='', max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_analyses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='students.student')),
            ],
            options={
                'ordering': ['-score', '-generated_at'],
                'indexes': [models.Index(fields=['college', 'risk_level'], name='analytics_s_college_ba54b5_idx'), models.Index(fields=['college', 'student', 'is_latest'], name='analytics_s_college_39307f_idx')],
            },
        ),
    ]
