# Generated by Django 5.1.15 on 2026-09-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text='Designated Head of Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='faculty.faculty'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('college', 'code'), name='unique_department_code_per_college'),
        ),
    ]
