# Generated by Django 5.1.15 on 2026-09-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='routed_tier',
            field=models.CharField(blank=True, default='', help_text='Target approval tier: MENTOR, HOD, or PRINCIPAL.', max_length=30),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='routed_to',
            field=models.ForeignKey(blank=True, help_text='The specific reviewer at this hierarchy level assigned to review this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leave_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
