# Generated by Django 5.1.15 on 2026-09-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('ACADEMIC', 'Academic'), ('EXAM', 'Examination'), ('EVENT', 'Campus Event'), ('ADMINISTRATIVE', 'Administrative'), ('HOLIDAY', 'Holiday Notice'), ('URGENT', 'Urgent Alert'), ('FEES', 'Fees & Finance')], default='ACADEMIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('FEE_DUE', 'Fee Due'), ('PAYMENT_SUCCESS', 'Payment Success'), ('ATTENDANCE_ALERT', 'Attendance Alert'), ('EXAM_RESULT', 'Exam Result'), ('LEAVE_STATUS', 'Leave Status Update'), ('MESSAGE', 'New Message'), ('PRINT_STATUS', 'Print Order Status'), ('LIBRARY_STATUS', 'Library Request Status'), ('FACILITY_STATUS', 'Facility Booking Status')], default='ANNOUNCEMENT', max_length=30),
        ),
    ]
