# Generated by Django 5.1.15 on 2026-09-06 06:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payslip_number', models.CharField(db_index=True, max_length=50)),
                ('month', models.PositiveSmallIntegerField(help_text='1 to 12')),
                ('year', models.PositiveSmallIntegerField()),
                ('working_days', models.PositiveSmallIntegerField(default=30)),
                ('present_days', models.PositiveSmallIntegerField(default=30)),
                ('leave_days', models.PositiveSmallIntegerField(default=0)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Disbursed / Paid')], default='PROCESSED', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(default='DIRECT_DEPOSIT', max_length=50)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='faculty.faculty')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('college', 'faculty', 'month', 'year'), name='unique_payslip_per_faculty_month'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('college', 'payslip_number'), name='unique_payslip_number_per_college')],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='House Rent Allowance', max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dearness Allowance', max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Provident Fund', max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TDS / Income Tax', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='colleges.college')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='faculty.faculty')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['college', 'is_deleted'], name='payroll_sal_college_ab9b2e_idx')],
            },
        ),
    ]
